// This file is auto-generated by tools/gen_component_index.zig. Do not edit manually.
// Regenerate with: zig build gen-component-index
//
// Maps a node's `component_name` to where that name is assigned in source,
// so DevTools can open the component's definition in an editor.

const std = @import("std");

pub const Entry = struct {
    name: []const u8,
    file: []const u8,
    line: u32,
    col: u32,
    /// Which source tree this came from (e.g. "zenit", "app").
    label: []const u8,
};

/// Sorted by `name`, so `lookup` can binary-search. Duplicate names are
/// possible (several components share a short name); `lookup` returns the
/// first and `lookupAll` returns the full run.
pub const entries = [_]Entry{
    .{ .name = "Accordion", .file = "src/ui/components/accordion/mod.zig", .line = 556, .col = 38, .label = "zenit" },
    .{ .name = "AccordionItem", .file = "src/ui/components/accordion/mod.zig", .line = 393, .col = 33, .label = "zenit" },
    .{ .name = "Alert", .file = "src/ui/components/alert/mod.zig", .line = 108, .col = 39, .label = "zenit" },
    .{ .name = "Badge", .file = "src/ui/components/badge/mod.zig", .line = 132, .col = 41, .label = "zenit" },
    .{ .name = "Badge", .file = "src/ui/components/badge/mod.zig", .line = 168, .col = 33, .label = "zenit" },
    .{ .name = "Breadcrumb", .file = "src/ui/components/breadcrumb/mod.zig", .line = 72, .col = 38, .label = "zenit" },
    .{ .name = "Button", .file = "src/ui/components/button/mod.zig", .line = 194, .col = 33, .label = "zenit" },
    .{ .name = "Button.content", .file = "src/ui/components/button/mod.zig", .line = 267, .col = 47, .label = "zenit" },
    .{ .name = "Button.spinner", .file = "src/ui/components/button/mod.zig", .line = 249, .col = 45, .label = "zenit" },
    .{ .name = "Calendar", .file = "src/ui/components/calendar/mod.zig", .line = 235, .col = 38, .label = "zenit" },
    .{ .name = "Card", .file = "src/ui/components/card/mod.zig", .line = 153, .col = 33, .label = "zenit" },
    .{ .name = "CardGrid", .file = "src/ui/components/card/mod.zig", .line = 234, .col = 29, .label = "zenit" },
    .{ .name = "Checkbox", .file = "src/ui/components/checkbox/mod.zig", .line = 223, .col = 38, .label = "zenit" },
    .{ .name = "Chip", .file = "src/ui/components/chip/mod.zig", .line = 111, .col = 33, .label = "zenit" },
    .{ .name = "ComboBox", .file = "src/ui/components/combo_box/mod.zig", .line = 331, .col = 36, .label = "zenit" },
    .{ .name = "DataTable", .file = "src/ui/components/data_table/mod.zig", .line = 420, .col = 29, .label = "zenit" },
    .{ .name = "DatePicker", .file = "src/ui/components/date_picker/mod.zig", .line = 136, .col = 47, .label = "zenit" },
    .{ .name = "DatePickerPanel", .file = "src/ui/components/date_picker/mod.zig", .line = 228, .col = 34, .label = "zenit" },
    .{ .name = "DateRangePicker", .file = "src/ui/components/date_range_picker/mod.zig", .line = 160, .col = 47, .label = "zenit" },
    .{ .name = "DateRangePickerPanel", .file = "src/ui/components/date_range_picker/mod.zig", .line = 231, .col = 34, .label = "zenit" },
    .{ .name = "DevtoolsOverlay", .file = "src/ui/core/devtools_overlay.zig", .line = 105, .col = 34, .label = "zenit" },
    .{ .name = "DevtoolsOverlayBox", .file = "src/ui/core/devtools_overlay.zig", .line = 129, .col = 28, .label = "zenit" },
    .{ .name = "DevtoolsOverlayLabel", .file = "src/ui/core/devtools_overlay.zig", .line = 149, .col = 33, .label = "zenit" },
    .{ .name = "Divider", .file = "src/ui/components/divider/mod.zig", .line = 159, .col = 37, .label = "zenit" },
    .{ .name = "Divider", .file = "src/ui/components/divider/mod.zig", .line = 168, .col = 33, .label = "zenit" },
    .{ .name = "DropdownMenu", .file = "src/ui/components/dropdown_menu/mod.zig", .line = 229, .col = 47, .label = "zenit" },
    .{ .name = "EditableText", .file = "src/ui/components/input/editable_text.zig", .line = 265, .col = 33, .label = "zenit" },
    .{ .name = "EditorTabs", .file = "src/ui/components/tabs/mod.zig", .line = 762, .col = 38, .label = "zenit" },
    .{ .name = "FileUpload", .file = "src/ui/components/file_upload/mod.zig", .line = 199, .col = 32, .label = "zenit" },
    .{ .name = "Form", .file = "src/ui/components/form/form_layout.zig", .line = 69, .col = 36, .label = "zenit" },
    .{ .name = "FormField", .file = "src/ui/components/form/form_field.zig", .line = 85, .col = 40, .label = "zenit" },
    .{ .name = "FormSection", .file = "src/ui/components/form/form_layout.zig", .line = 86, .col = 32, .label = "zenit" },
    .{ .name = "GlassBox", .file = "src/ui/components/glass_box/mod.zig", .line = 189, .col = 33, .label = "zenit" },
    .{ .name = "Grid", .file = "src/ui/components/grid/mod.zig", .line = 96, .col = 33, .label = "zenit" },
    .{ .name = "Grid.Cell", .file = "src/ui/components/grid/mod.zig", .line = 545, .col = 33, .label = "zenit" },
    .{ .name = "Grid.Content", .file = "src/ui/components/grid/mod.zig", .line = 139, .col = 39, .label = "zenit" },
    .{ .name = "Grid.ScrollArea", .file = "src/ui/components/grid/mod.zig", .line = 134, .col = 41, .label = "zenit" },
    .{ .name = "Group", .file = "src/ui/components/group/mod.zig", .line = 70, .col = 38, .label = "zenit" },
    .{ .name = "Input", .file = "src/ui/components/input/mod.zig", .line = 317, .col = 36, .label = "zenit" },
    .{ .name = "Menu", .file = "src/ui/components/menu/mod.zig", .line = 174, .col = 47, .label = "zenit" },
    .{ .name = "Modal", .file = "src/ui/components/modal/mod.zig", .line = 126, .col = 36, .label = "zenit" },
    .{ .name = "MyCustomTrigger", .file = "src/ui/core/tests.zig", .line = 11433, .col = 34, .label = "zenit" },
    .{ .name = "Notification", .file = "src/ui/components/notification/card.zig", .line = 301, .col = 35, .label = "zenit" },
    .{ .name = "Notification.action", .file = "src/ui/components/notification/card.zig", .line = 593, .col = 40, .label = "zenit" },
    .{ .name = "Notification.close", .file = "src/ui/components/notification/card.zig", .line = 375, .col = 30, .label = "zenit" },
    .{ .name = "Notification.content", .file = "src/ui/components/notification/card.zig", .line = 440, .col = 29, .label = "zenit" },
    .{ .name = "Notification.pill", .file = "src/ui/components/notification/mod.zig", .line = 195, .col = 33, .label = "zenit" },
    .{ .name = "Notification.surface", .file = "src/ui/components/notification/card.zig", .line = 316, .col = 32, .label = "zenit" },
    .{ .name = "NotificationViewport", .file = "src/ui/components/notification/mod.zig", .line = 174, .col = 38, .label = "zenit" },
    .{ .name = "NumberStepper", .file = "src/ui/components/number_stepper/mod.zig", .line = 167, .col = 32, .label = "zenit" },
    .{ .name = "Popover", .file = "src/ui/components/popover/mod.zig", .line = 291, .col = 36, .label = "zenit" },
    .{ .name = "PopoverContent", .file = "src/ui/components/popover/mod.zig", .line = 323, .col = 44, .label = "zenit" },
    .{ .name = "Progress", .file = "src/ui/components/progress/mod.zig", .line = 123, .col = 38, .label = "zenit" },
    .{ .name = "Radio", .file = "src/ui/components/checkbox/mod.zig", .line = 340, .col = 38, .label = "zenit" },
    .{ .name = "RadioGroup", .file = "src/ui/components/checkbox/mod.zig", .line = 528, .col = 38, .label = "zenit" },
    .{ .name = "Rate", .file = "src/ui/components/rate/mod.zig", .line = 191, .col = 38, .label = "zenit" },
    .{ .name = "ScrollArea", .file = "src/ui/components/scroll_area/mod.zig", .line = 107, .col = 38, .label = "zenit" },
    .{ .name = "Select", .file = "src/ui/components/select/mod.zig", .line = 630, .col = 36, .label = "zenit" },
    .{ .name = "SelectHeadless", .file = "src/ui/components/select_headless/mount.zig", .line = 686, .col = 36, .label = "zenit" },
    .{ .name = "Sheet", .file = "src/ui/components/sheet/mod.zig", .line = 126, .col = 36, .label = "zenit" },
    .{ .name = "Skeleton", .file = "src/ui/components/skeleton/mod.zig", .line = 124, .col = 38, .label = "zenit" },
    .{ .name = "Skeleton", .file = "src/ui/components/skeleton/mod.zig", .line = 157, .col = 29, .label = "zenit" },
    .{ .name = "Slider", .file = "src/ui/components/slider/mod.zig", .line = 212, .col = 38, .label = "zenit" },
    .{ .name = "SnapshotLayer", .file = "src/ui/components/snapshot_layer.zig", .line = 114, .col = 34, .label = "zenit" },
    .{ .name = "Spinner", .file = "src/ui/components/spinner/mod.zig", .line = 137, .col = 38, .label = "zenit" },
    .{ .name = "StatusBadge", .file = "src/ui/components/badge/mod.zig", .line = 227, .col = 38, .label = "zenit" },
    .{ .name = "Steps", .file = "src/ui/components/steps/mod.zig", .line = 107, .col = 38, .label = "zenit" },
    .{ .name = "Switch", .file = "src/ui/components/checkbox/mod.zig", .line = 753, .col = 38, .label = "zenit" },
    .{ .name = "TabHighlight", .file = "src/ui/components/tabs/mod.zig", .line = 437, .col = 42, .label = "zenit" },
    .{ .name = "TabPanel", .file = "src/ui/components/tabs/mod.zig", .line = 696, .col = 37, .label = "zenit" },
    .{ .name = "TabPanel", .file = "src/ui/components/tabs/mod.zig", .line = 710, .col = 33, .label = "zenit" },
    .{ .name = "Table", .file = "src/ui/components/table/mod.zig", .line = 207, .col = 40, .label = "zenit" },
    .{ .name = "Tabs", .file = "src/ui/components/tabs/mod.zig", .line = 472, .col = 38, .label = "zenit" },
    .{ .name = "Tag", .file = "src/ui/components/tag/mod.zig", .line = 171, .col = 37, .label = "zenit" },
    .{ .name = "TagsInput", .file = "src/ui/components/tags_input/mod.zig", .line = 220, .col = 32, .label = "zenit" },
    .{ .name = "Target", .file = "src/ui/core/devtools_overlay.zig", .line = 385, .col = 31, .label = "zenit" },
    .{ .name = "Textarea", .file = "src/ui/components/input/textarea.zig", .line = 2229, .col = 36, .label = "zenit" },
    .{ .name = "Timeline", .file = "src/ui/components/timeline/mod.zig", .line = 82, .col = 38, .label = "zenit" },
    .{ .name = "Tooltip", .file = "src/ui/components/tooltip/mod.zig", .line = 86, .col = 43, .label = "zenit" },
    .{ .name = "TooltipContent", .file = "src/ui/components/tooltip/mod.zig", .line = 88, .col = 43, .label = "zenit" },
    .{ .name = "Tree", .file = "src/ui/components/tree/mod.zig", .line = 302, .col = 38, .label = "zenit" },
    .{ .name = "VirtualList", .file = "src/ui/components/virtual_list/mod.zig", .line = 826, .col = 41, .label = "zenit" },
    .{ .name = "WindowOverlayPortal", .file = "src/ui/core.zig", .line = 1436, .col = 35, .label = "zenit" },
};

/// First entry whose name matches, or null. O(log n).
pub fn lookup(name: []const u8) ?Entry {
    const run = lookupAll(name);
    return if (run.len == 0) null else run[0];
}

/// Every entry matching `name` (contiguous, since `entries` is sorted).
pub fn lookupAll(name: []const u8) []const Entry {
    var lo: usize = 0;
    var hi: usize = entries.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (std.mem.lessThan(u8, entries[mid].name, name)) lo = mid + 1 else hi = mid;
    }
    var end = lo;
    while (end < entries.len and std.mem.eql(u8, entries[end].name, name)) end += 1;
    return entries[lo..end];
}
