// This file is auto-generated by tools/gen_svg_assets.zig. Do not edit manually.
// Regenerate with: zig build gen-icons

const std = @import("std");
const icon_ir = @import("icon_ir");

pub const Asset = icon_ir.Asset;

pub const calendar = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 8, .y = 2 },
        .{ .x = 8, .y = 5 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 16, .y = 2 },
        .{ .x = 16, .y = 5 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = false },
    };
    const s2_c0_pts = [_]icon_ir.Point{
        .{ .x = 3, .y = 3 },
        .{ .x = 21, .y = 3 },
        .{ .x = 21, .y = 21 },
        .{ .x = 3, .y = 21 },
    };
    const s2_contours = [_]icon_ir.Contour{
        .{ .points = &s2_c0_pts, .closed = true },
    };
    const s3_c0_pts = [_]icon_ir.Point{
        .{ .x = 3, .y = 9 },
        .{ .x = 21, .y = 9 },
    };
    const s3_contours = [_]icon_ir.Contour{
        .{ .points = &s3_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s2_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s3_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/calendar.svg"), .default_width = 24, .default_height = 24, .icon_id = 0, .reps = &zi_reps };
};
pub const check = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 20, .y = 6 },
        .{ .x = 9, .y = 17 },
        .{ .x = 4, .y = 12 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/check.svg"), .default_width = 24, .default_height = 24, .icon_id = 1, .reps = &zi_reps };
};
pub const chevron_down = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 6, .y = 9 },
        .{ .x = 12, .y = 15 },
        .{ .x = 18, .y = 9 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/chevron_down.svg"), .default_width = 24, .default_height = 24, .icon_id = 2, .reps = &zi_reps };
};
pub const chevron_left = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 15, .y = 18 },
        .{ .x = 9, .y = 12 },
        .{ .x = 15, .y = 6 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/chevron_left.svg"), .default_width = 24, .default_height = 24, .icon_id = 3, .reps = &zi_reps };
};
pub const chevron_right = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 9, .y = 18 },
        .{ .x = 15, .y = 12 },
        .{ .x = 9, .y = 6 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/chevron_right.svg"), .default_width = 24, .default_height = 24, .icon_id = 4, .reps = &zi_reps };
};
pub const chevron_up = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 18, .y = 15 },
        .{ .x = 12, .y = 9 },
        .{ .x = 6, .y = 15 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/chevron_up.svg"), .default_width = 24, .default_height = 24, .icon_id = 5, .reps = &zi_reps };
};
pub const code = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 16, .y = 18 },
        .{ .x = 22, .y = 12 },
        .{ .x = 16, .y = 6 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 8, .y = 6 },
        .{ .x = 2, .y = 12 },
        .{ .x = 8, .y = 18 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/code.svg"), .default_width = 24, .default_height = 24, .icon_id = 6, .reps = &zi_reps };
};
pub const file_text = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 6, .y = 22 },
        .{ .x = 5.234633, .y = 21.84776 },
        .{ .x = 4.5857863, .y = 21.414213 },
        .{ .x = 4.1522408, .y = 20.765366 },
        .{ .x = 4, .y = 20 },
        .{ .x = 4, .y = 4 },
        .{ .x = 4.1522408, .y = 3.234633 },
        .{ .x = 4.585787, .y = 2.5857863 },
        .{ .x = 5.234633, .y = 2.152241 },
        .{ .x = 6, .y = 2 },
        .{ .x = 14, .y = 2 },
        .{ .x = 14.470305, .y = 2.0457542 },
        .{ .x = 14.92253, .y = 2.1827686 },
        .{ .x = 15.339145, .y = 2.4057312 },
        .{ .x = 15.704, .y = 2.7059999 },
        .{ .x = 19.292, .y = 6.2939997 },
        .{ .x = 19.59309, .y = 6.659089 },
        .{ .x = 19.816692, .y = 7.0761614 },
        .{ .x = 19.95411, .y = 7.5290003 },
        .{ .x = 20, .y = 8 },
        .{ .x = 20, .y = 20 },
        .{ .x = 19.84776, .y = 20.765368 },
        .{ .x = 19.414213, .y = 21.414213 },
        .{ .x = 18.765368, .y = 21.84776 },
        .{ .x = 18, .y = 22 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = true },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 14, .y = 2 },
        .{ .x = 14, .y = 7 },
        .{ .x = 14.07612, .y = 7.3826833 },
        .{ .x = 14.292893, .y = 7.7071066 },
        .{ .x = 14.617316, .y = 7.9238796 },
        .{ .x = 15, .y = 8 },
        .{ .x = 20, .y = 8 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = false },
    };
    const s2_c0_pts = [_]icon_ir.Point{
        .{ .x = 10, .y = 9 },
        .{ .x = 8, .y = 9 },
    };
    const s2_contours = [_]icon_ir.Contour{
        .{ .points = &s2_c0_pts, .closed = false },
    };
    const s3_c0_pts = [_]icon_ir.Point{
        .{ .x = 16, .y = 13 },
        .{ .x = 8, .y = 13 },
    };
    const s3_contours = [_]icon_ir.Contour{
        .{ .points = &s3_c0_pts, .closed = false },
    };
    const s4_c0_pts = [_]icon_ir.Point{
        .{ .x = 16, .y = 17 },
        .{ .x = 8, .y = 17 },
    };
    const s4_contours = [_]icon_ir.Contour{
        .{ .points = &s4_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s2_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s3_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s4_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/file_text.svg"), .default_width = 24, .default_height = 24, .icon_id = 7, .reps = &zi_reps };
};
pub const folder = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 20, .y = 20 },
        .{ .x = 20.765368, .y = 19.84776 },
        .{ .x = 21.414213, .y = 19.414213 },
        .{ .x = 21.84776, .y = 18.765368 },
        .{ .x = 22, .y = 18 },
        .{ .x = 22, .y = 8 },
        .{ .x = 21.84776, .y = 7.234633 },
        .{ .x = 21.414213, .y = 6.5857863 },
        .{ .x = 20.765368, .y = 6.1522408 },
        .{ .x = 20, .y = 6 },
        .{ .x = 12.1, .y = 6 },
        .{ .x = 11.605435, .y = 5.9428816 },
        .{ .x = 11.140301, .y = 5.76538 },
        .{ .x = 10.733418, .y = 5.478494 },
        .{ .x = 10.41, .y = 5.1 },
        .{ .x = 9.6, .y = 3.9 },
        .{ .x = 9.280262, .y = 3.5249052 },
        .{ .x = 8.878499, .y = 3.2393963 },
        .{ .x = 8.419112, .y = 3.0608125 },
        .{ .x = 7.93, .y = 3 },
        .{ .x = 4, .y = 3 },
        .{ .x = 3.234633, .y = 3.152241 },
        .{ .x = 2.5857863, .y = 3.5857863 },
        .{ .x = 2.1522408, .y = 4.2346334 },
        .{ .x = 2, .y = 5 },
        .{ .x = 2, .y = 18 },
        .{ .x = 2.1522408, .y = 18.765366 },
        .{ .x = 2.5857863, .y = 19.414213 },
        .{ .x = 3.234633, .y = 19.84776 },
        .{ .x = 4, .y = 20 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = true },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/folder.svg"), .default_width = 24, .default_height = 24, .icon_id = 8, .reps = &zi_reps };
};
pub const folder_open = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 6, .y = 14 },
        .{ .x = 7.5, .y = 11.1 },
        .{ .x = 7.805023, .y = 10.655685 },
        .{ .x = 8.21761, .y = 10.308948 },
        .{ .x = 8.7078, .y = 10.084964 },
        .{ .x = 9.24, .y = 10 },
        .{ .x = 20, .y = 10 },
        .{ .x = 20.714218, .y = 10.130533 },
        .{ .x = 21.334772, .y = 10.507434 },
        .{ .x = 21.779886, .y = 11.081035 },
        .{ .x = 21.990898, .y = 11.775741 },
        .{ .x = 21.940002, .y = 12.5 },
        .{ .x = 20.400002, .y = 18.5 },
        .{ .x = 20.132158, .y = 19.102573 },
        .{ .x = 19.682919, .y = 19.585295 },
        .{ .x = 19.101116, .y = 19.895683 },
        .{ .x = 18.45, .y = 20 },
        .{ .x = 4, .y = 20 },
        .{ .x = 3.234633, .y = 19.84776 },
        .{ .x = 2.5857863, .y = 19.414213 },
        .{ .x = 2.1522408, .y = 18.765366 },
        .{ .x = 2, .y = 18 },
        .{ .x = 2, .y = 5 },
        .{ .x = 2.152241, .y = 4.234633 },
        .{ .x = 2.5857868, .y = 3.5857863 },
        .{ .x = 3.234633, .y = 3.152241 },
        .{ .x = 4, .y = 3 },
        .{ .x = 7.9, .y = 3 },
        .{ .x = 8.394565, .y = 3.0571182 },
        .{ .x = 8.859699, .y = 3.23462 },
        .{ .x = 9.266582, .y = 3.521506 },
        .{ .x = 9.59, .y = 3.9 },
        .{ .x = 10.400001, .y = 5.1000004 },
        .{ .x = 10.719739, .y = 5.475095 },
        .{ .x = 11.121501, .y = 5.7606034 },
        .{ .x = 11.580889, .y = 5.939187 },
        .{ .x = 12.070001, .y = 6 },
        .{ .x = 18, .y = 6.0000005 },
        .{ .x = 18.765368, .y = 6.1522408 },
        .{ .x = 19.414213, .y = 6.5857863 },
        .{ .x = 19.84776, .y = 7.234633 },
        .{ .x = 20, .y = 7.9999995 },
        .{ .x = 20, .y = 10 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/folder_open.svg"), .default_width = 24, .default_height = 24, .icon_id = 9, .reps = &zi_reps };
};
pub const link = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 10, .y = 13 },
        .{ .x = 11.239739, .y = 14.171621 },
        .{ .x = 12.801179, .y = 14.858317 },
        .{ .x = 14.50259, .y = 14.980169 },
        .{ .x = 16.145952, .y = 14.522993 },
        .{ .x = 17.54, .y = 13.54 },
        .{ .x = 20.54, .y = 10.54 },
        .{ .x = 21.587502, .y = 8.919487 },
        .{ .x = 21.943365, .y = 7.022996 },
        .{ .x = 21.554594, .y = 5.1329756 },
        .{ .x = 20.479088, .y = 3.5309124 },
        .{ .x = 18.877026, .y = 2.4554062 },
        .{ .x = 16.987005, .y = 2.0666351 },
        .{ .x = 15.090513, .y = 2.4224997 },
        .{ .x = 13.47, .y = 3.4700003 },
        .{ .x = 11.750001, .y = 5.18 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 14, .y = 11 },
        .{ .x = 12.760262, .y = 9.828379 },
        .{ .x = 11.198821, .y = 9.141683 },
        .{ .x = 9.49741, .y = 9.019831 },
        .{ .x = 7.8540487, .y = 9.477006 },
        .{ .x = 6.46, .y = 10.459999 },
        .{ .x = 3.46, .y = 13.46 },
        .{ .x = 2.4124875, .y = 15.080515 },
        .{ .x = 2.0566154, .y = 16.977013 },
        .{ .x = 2.4453845, .y = 18.86704 },
        .{ .x = 3.5208933, .y = 20.469109 },
        .{ .x = 5.1229625, .y = 21.544617 },
        .{ .x = 7.012992, .y = 21.933386 },
        .{ .x = 8.909489, .y = 21.577513 },
        .{ .x = 10.530001, .y = 20.53 },
        .{ .x = 12.240001, .y = 18.82 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/link.svg"), .default_width = 24, .default_height = 24, .icon_id = 10, .reps = &zi_reps };
};
pub const mark = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 22, .y = 12 },
        .{ .x = 21.951847, .y = 12.980171 },
        .{ .x = 21.807854, .y = 13.950903 },
        .{ .x = 21.569405, .y = 14.902847 },
        .{ .x = 21.238796, .y = 15.826835 },
        .{ .x = 20.819212, .y = 16.713966 },
        .{ .x = 20.314697, .y = 17.555702 },
        .{ .x = 19.730104, .y = 18.343933 },
        .{ .x = 19.071068, .y = 19.071068 },
        .{ .x = 18.343933, .y = 19.730104 },
        .{ .x = 17.555702, .y = 20.314697 },
        .{ .x = 16.713966, .y = 20.819214 },
        .{ .x = 15.826834, .y = 21.238796 },
        .{ .x = 14.902846, .y = 21.569405 },
        .{ .x = 13.950902, .y = 21.807854 },
        .{ .x = 12.980171, .y = 21.951847 },
        .{ .x = 12, .y = 22 },
        .{ .x = 11.019828, .y = 21.951847 },
        .{ .x = 10.049097, .y = 21.807854 },
        .{ .x = 9.097153, .y = 21.569403 },
        .{ .x = 8.173164, .y = 21.238796 },
        .{ .x = 7.2860317, .y = 20.819212 },
        .{ .x = 6.4442964, .y = 20.314695 },
        .{ .x = 5.6560674, .y = 19.730104 },
        .{ .x = 4.928932, .y = 19.071068 },
        .{ .x = 4.269895, .y = 18.343933 },
        .{ .x = 3.6853037, .y = 17.555702 },
        .{ .x = 3.1807861, .y = 16.713966 },
        .{ .x = 2.7612038, .y = 15.826833 },
        .{ .x = 2.4305964, .y = 14.902847 },
        .{ .x = 2.1921473, .y = 13.950903 },
        .{ .x = 2.048153, .y = 12.980171 },
        .{ .x = 2, .y = 11.999999 },
        .{ .x = 2.048153, .y = 11.019827 },
        .{ .x = 2.1921473, .y = 10.049095 },
        .{ .x = 2.4305973, .y = 9.097151 },
        .{ .x = 2.7612047, .y = 8.173165 },
        .{ .x = 3.180788, .y = 7.286032 },
        .{ .x = 3.6853046, .y = 6.444297 },
        .{ .x = 4.2698965, .y = 5.656066 },
        .{ .x = 4.9289336, .y = 4.928931 },
        .{ .x = 5.656067, .y = 4.2698956 },
        .{ .x = 6.4442997, .y = 3.6853027 },
        .{ .x = 7.286033, .y = 3.180787 },
        .{ .x = 8.173168, .y = 2.7612028 },
        .{ .x = 9.097155, .y = 2.4305964 },
        .{ .x = 10.049096, .y = 2.1921473 },
        .{ .x = 11.019831, .y = 2.048153 },
        .{ .x = 12, .y = 2 },
        .{ .x = 12.980174, .y = 2.048153 },
        .{ .x = 13.950904, .y = 2.1921473 },
        .{ .x = 14.90285, .y = 2.4305973 },
        .{ .x = 15.826836, .y = 2.7612057 },
        .{ .x = 16.713966, .y = 3.180787 },
        .{ .x = 17.555704, .y = 3.6853056 },
        .{ .x = 18.343933, .y = 4.2698956 },
        .{ .x = 19.07107, .y = 4.9289346 },
        .{ .x = 19.730106, .y = 5.6560683 },
        .{ .x = 20.314697, .y = 6.444297 },
        .{ .x = 20.819214, .y = 7.2860346 },
        .{ .x = 21.238796, .y = 8.173166 },
        .{ .x = 21.569405, .y = 9.097157 },
        .{ .x = 21.807854, .y = 10.049098 },
        .{ .x = 21.951847, .y = 11.019833 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = true },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 22, .y = 12 },
        .{ .x = 18, .y = 12 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = false },
    };
    const s2_c0_pts = [_]icon_ir.Point{
        .{ .x = 6, .y = 12 },
        .{ .x = 2, .y = 12 },
    };
    const s2_contours = [_]icon_ir.Contour{
        .{ .points = &s2_c0_pts, .closed = false },
    };
    const s3_c0_pts = [_]icon_ir.Point{
        .{ .x = 12, .y = 6 },
        .{ .x = 12, .y = 2 },
    };
    const s3_contours = [_]icon_ir.Contour{
        .{ .points = &s3_c0_pts, .closed = false },
    };
    const s4_c0_pts = [_]icon_ir.Point{
        .{ .x = 12, .y = 22 },
        .{ .x = 12, .y = 18 },
    };
    const s4_contours = [_]icon_ir.Contour{
        .{ .points = &s4_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s2_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s3_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s4_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/mark.svg"), .default_width = 24, .default_height = 24, .icon_id = 11, .reps = &zi_reps };
};
pub const plus = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 5, .y = 12 },
        .{ .x = 19, .y = 12 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 12, .y = 5 },
        .{ .x = 12, .y = 19 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/plus.svg"), .default_width = 24, .default_height = 24, .icon_id = 12, .reps = &zi_reps };
};
pub const scan = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 3, .y = 7 },
        .{ .x = 3, .y = 5 },
        .{ .x = 3.152241, .y = 4.234633 },
        .{ .x = 3.5857868, .y = 3.5857863 },
        .{ .x = 4.234633, .y = 3.152241 },
        .{ .x = 5, .y = 3 },
        .{ .x = 7, .y = 3 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 17, .y = 3 },
        .{ .x = 19, .y = 3 },
        .{ .x = 19.765368, .y = 3.152241 },
        .{ .x = 20.414213, .y = 3.5857863 },
        .{ .x = 20.84776, .y = 4.234633 },
        .{ .x = 21, .y = 5 },
        .{ .x = 21, .y = 7 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = false },
    };
    const s2_c0_pts = [_]icon_ir.Point{
        .{ .x = 21, .y = 17 },
        .{ .x = 21, .y = 19 },
        .{ .x = 20.84776, .y = 19.765368 },
        .{ .x = 20.414213, .y = 20.414213 },
        .{ .x = 19.765368, .y = 20.84776 },
        .{ .x = 19, .y = 21 },
        .{ .x = 17, .y = 21 },
    };
    const s2_contours = [_]icon_ir.Contour{
        .{ .points = &s2_c0_pts, .closed = false },
    };
    const s3_c0_pts = [_]icon_ir.Point{
        .{ .x = 7, .y = 21 },
        .{ .x = 5, .y = 21 },
        .{ .x = 4.234633, .y = 20.84776 },
        .{ .x = 3.5857863, .y = 20.414213 },
        .{ .x = 3.1522408, .y = 19.765366 },
        .{ .x = 3, .y = 19 },
        .{ .x = 3, .y = 17 },
    };
    const s3_contours = [_]icon_ir.Contour{
        .{ .points = &s3_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s2_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s3_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/scan.svg"), .default_width = 24, .default_height = 24, .icon_id = 13, .reps = &zi_reps };
};
pub const search = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 21, .y = 21 },
        .{ .x = 16.66, .y = 16.66 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 19, .y = 11 },
        .{ .x = 18.961477, .y = 11.784137 },
        .{ .x = 18.846283, .y = 12.560722 },
        .{ .x = 18.655523, .y = 13.322277 },
        .{ .x = 18.391037, .y = 14.061468 },
        .{ .x = 18.05537, .y = 14.7711735 },
        .{ .x = 17.651756, .y = 15.444562 },
        .{ .x = 17.184084, .y = 16.075146 },
        .{ .x = 16.656855, .y = 16.656855 },
        .{ .x = 16.075146, .y = 17.184084 },
        .{ .x = 15.444561, .y = 17.651756 },
        .{ .x = 14.7711735, .y = 18.05537 },
        .{ .x = 14.061467, .y = 18.391037 },
        .{ .x = 13.322277, .y = 18.655523 },
        .{ .x = 12.560722, .y = 18.846283 },
        .{ .x = 11.784137, .y = 18.961477 },
        .{ .x = 11, .y = 19 },
        .{ .x = 10.215862, .y = 18.961477 },
        .{ .x = 9.439278, .y = 18.846283 },
        .{ .x = 8.677722, .y = 18.655521 },
        .{ .x = 7.938532, .y = 18.391037 },
        .{ .x = 7.2288256, .y = 18.05537 },
        .{ .x = 6.555437, .y = 17.651756 },
        .{ .x = 5.924854, .y = 17.184084 },
        .{ .x = 5.343146, .y = 16.656855 },
        .{ .x = 4.815916, .y = 16.075146 },
        .{ .x = 4.3482428, .y = 15.444561 },
        .{ .x = 3.9446292, .y = 14.7711735 },
        .{ .x = 3.608963, .y = 14.061466 },
        .{ .x = 3.3444772, .y = 13.322278 },
        .{ .x = 3.1537175, .y = 12.560722 },
        .{ .x = 3.0385222, .y = 11.784137 },
        .{ .x = 3, .y = 10.999999 },
        .{ .x = 3.0385222, .y = 10.215862 },
        .{ .x = 3.153718, .y = 9.439276 },
        .{ .x = 3.3444777, .y = 8.677721 },
        .{ .x = 3.608964, .y = 7.9385324 },
        .{ .x = 3.9446301, .y = 7.2288256 },
        .{ .x = 4.3482437, .y = 6.5554376 },
        .{ .x = 4.815917, .y = 5.924853 },
        .{ .x = 5.343147, .y = 5.343145 },
        .{ .x = 5.9248533, .y = 4.8159165 },
        .{ .x = 6.55544, .y = 4.348242 },
        .{ .x = 7.2288265, .y = 3.9446297 },
        .{ .x = 7.9385347, .y = 3.6089625 },
        .{ .x = 8.677724, .y = 3.3444772 },
        .{ .x = 9.439277, .y = 3.153718 },
        .{ .x = 10.215864, .y = 3.0385222 },
        .{ .x = 11, .y = 3 },
        .{ .x = 11.78414, .y = 3.0385222 },
        .{ .x = 12.560723, .y = 3.153718 },
        .{ .x = 13.32228, .y = 3.3444781 },
        .{ .x = 14.061469, .y = 3.6089644 },
        .{ .x = 14.7711735, .y = 3.9446297 },
        .{ .x = 15.444563, .y = 4.348244 },
        .{ .x = 16.075146, .y = 4.8159165 },
        .{ .x = 16.656857, .y = 5.3431478 },
        .{ .x = 17.184084, .y = 5.9248548 },
        .{ .x = 17.651756, .y = 6.5554376 },
        .{ .x = 18.05537, .y = 7.2288275 },
        .{ .x = 18.391037, .y = 7.938533 },
        .{ .x = 18.655523, .y = 8.677725 },
        .{ .x = 18.846283, .y = 9.439278 },
        .{ .x = 18.96148, .y = 10.215866 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = true },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/search.svg"), .default_width = 24, .default_height = 24, .icon_id = 14, .reps = &zi_reps };
};
pub const star = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 11.525, .y = 2.295 },
        .{ .x = 11.642318, .y = 2.1390014 },
        .{ .x = 11.808148, .y = 2.036049 },
        .{ .x = 12, .y = 2.0001066 },
        .{ .x = 12.191852, .y = 2.0360491 },
        .{ .x = 12.357682, .y = 2.1390014 },
        .{ .x = 12.475, .y = 2.295 },
        .{ .x = 14.785, .y = 6.974 },
        .{ .x = 15.065199, .y = 7.4019475 },
        .{ .x = 15.439624, .y = 7.7504535 },
        .{ .x = 15.8865385, .y = 7.9992857 },
        .{ .x = 16.38, .y = 8.134 },
        .{ .x = 21.546, .y = 8.889999 },
        .{ .x = 21.730915, .y = 8.953192 },
        .{ .x = 21.88036, .y = 9.079099 },
        .{ .x = 21.97402, .y = 9.250606 },
        .{ .x = 21.999163, .y = 9.444395 },
        .{ .x = 21.95237, .y = 9.634124 },
        .{ .x = 21.84, .y = 9.794 },
        .{ .x = 18.104, .y = 13.431999 },
        .{ .x = 17.782936, .y = 13.831171 },
        .{ .x = 17.566833, .y = 14.295629 },
        .{ .x = 17.468277, .y = 14.798327 },
        .{ .x = 17.493, .y = 15.309999 },
        .{ .x = 18.375, .y = 20.449999 },
        .{ .x = 18.372755, .y = 20.646257 },
        .{ .x = 18.299244, .y = 20.828243 },
        .{ .x = 18.164543, .y = 20.970997 },
        .{ .x = 17.98713, .y = 21.054941 },
        .{ .x = 17.79133, .y = 21.068563 },
        .{ .x = 17.604, .y = 21.009998 },
        .{ .x = 12.986, .y = 18.581999 },
        .{ .x = 12.5075245, .y = 18.40046 },
        .{ .x = 11.9995, .y = 18.338749 },
        .{ .x = 11.491477, .y = 18.40046 },
        .{ .x = 11.0130005, .y = 18.581999 },
        .{ .x = 6.396, .y = 21.01 },
        .{ .x = 6.208837, .y = 21.068089 },
        .{ .x = 6.0133605, .y = 21.054193 },
        .{ .x = 5.836295, .y = 20.970219 },
        .{ .x = 5.701849, .y = 20.82764 },
        .{ .x = 5.6284037, .y = 20.645954 },
        .{ .x = 5.6259995, .y = 20.449999 },
        .{ .x = 6.507, .y = 15.311001 },
        .{ .x = 6.5320096, .y = 14.799056 },
        .{ .x = 6.433538, .y = 14.296048 },
        .{ .x = 6.21733, .y = 13.831326 },
        .{ .x = 5.896, .y = 13.432001 },
        .{ .x = 2.16, .y = 9.795 },
        .{ .x = 2.046578, .y = 9.635004 },
        .{ .x = 1.999104, .y = 9.4447155 },
        .{ .x = 2.0240788, .y = 9.250191 },
        .{ .x = 2.1180825, .y = 9.078067 },
        .{ .x = 2.2682436, .y = 8.951912 },
        .{ .x = 2.4540002, .y = 8.889 },
        .{ .x = 7.619, .y = 8.134 },
        .{ .x = 8.113065, .y = 7.9997067 },
        .{ .x = 8.560583, .y = 7.7509866 },
        .{ .x = 8.935504, .y = 7.4023185 },
        .{ .x = 9.216, .y = 6.974 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = true },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/star.svg"), .default_width = 24, .default_height = 24, .icon_id = 15, .reps = &zi_reps };
};
pub const star_filled = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 11.525, .y = 2.295 },
        .{ .x = 11.642318, .y = 2.1390014 },
        .{ .x = 11.808148, .y = 2.036049 },
        .{ .x = 12, .y = 2.0001066 },
        .{ .x = 12.191852, .y = 2.0360491 },
        .{ .x = 12.357682, .y = 2.1390014 },
        .{ .x = 12.475, .y = 2.295 },
        .{ .x = 14.785, .y = 6.974 },
        .{ .x = 15.065199, .y = 7.4019475 },
        .{ .x = 15.439624, .y = 7.7504535 },
        .{ .x = 15.8865385, .y = 7.9992857 },
        .{ .x = 16.38, .y = 8.134 },
        .{ .x = 21.546, .y = 8.889999 },
        .{ .x = 21.730915, .y = 8.953192 },
        .{ .x = 21.88036, .y = 9.079099 },
        .{ .x = 21.97402, .y = 9.250606 },
        .{ .x = 21.999163, .y = 9.444395 },
        .{ .x = 21.95237, .y = 9.634124 },
        .{ .x = 21.84, .y = 9.794 },
        .{ .x = 18.104, .y = 13.431999 },
        .{ .x = 17.782936, .y = 13.831171 },
        .{ .x = 17.566833, .y = 14.295629 },
        .{ .x = 17.468277, .y = 14.798327 },
        .{ .x = 17.493, .y = 15.309999 },
        .{ .x = 18.375, .y = 20.449999 },
        .{ .x = 18.372755, .y = 20.646257 },
        .{ .x = 18.299244, .y = 20.828243 },
        .{ .x = 18.164543, .y = 20.970997 },
        .{ .x = 17.98713, .y = 21.054941 },
        .{ .x = 17.79133, .y = 21.068563 },
        .{ .x = 17.604, .y = 21.009998 },
        .{ .x = 12.986, .y = 18.581999 },
        .{ .x = 12.5075245, .y = 18.40046 },
        .{ .x = 11.9995, .y = 18.338749 },
        .{ .x = 11.491477, .y = 18.40046 },
        .{ .x = 11.0130005, .y = 18.581999 },
        .{ .x = 6.396, .y = 21.01 },
        .{ .x = 6.208837, .y = 21.068089 },
        .{ .x = 6.0133605, .y = 21.054193 },
        .{ .x = 5.836295, .y = 20.970219 },
        .{ .x = 5.701849, .y = 20.82764 },
        .{ .x = 5.6284037, .y = 20.645954 },
        .{ .x = 5.6259995, .y = 20.449999 },
        .{ .x = 6.507, .y = 15.311001 },
        .{ .x = 6.5320096, .y = 14.799056 },
        .{ .x = 6.433538, .y = 14.296048 },
        .{ .x = 6.21733, .y = 13.831326 },
        .{ .x = 5.896, .y = 13.432001 },
        .{ .x = 2.16, .y = 9.795 },
        .{ .x = 2.046578, .y = 9.635004 },
        .{ .x = 1.999104, .y = 9.4447155 },
        .{ .x = 2.0240788, .y = 9.250191 },
        .{ .x = 2.1180825, .y = 9.078067 },
        .{ .x = 2.2682436, .y = 8.951912 },
        .{ .x = 2.4540002, .y = 8.889 },
        .{ .x = 7.619, .y = 8.134 },
        .{ .x = 8.113065, .y = 7.9997067 },
        .{ .x = 8.560583, .y = 7.7509866 },
        .{ .x = 8.935504, .y = 7.4023185 },
        .{ .x = 9.216, .y = 6.974 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = true },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = true, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/star_filled.svg"), .default_width = 24, .default_height = 24, .icon_id = 16, .reps = &zi_reps };
};
pub const x_close = blk: {
    const s0_c0_pts = [_]icon_ir.Point{
        .{ .x = 18, .y = 6 },
        .{ .x = 6, .y = 18 },
    };
    const s0_contours = [_]icon_ir.Contour{
        .{ .points = &s0_c0_pts, .closed = false },
    };
    const s1_c0_pts = [_]icon_ir.Point{
        .{ .x = 6, .y = 6 },
        .{ .x = 18, .y = 18 },
    };
    const s1_contours = [_]icon_ir.Contour{
        .{ .points = &s1_c0_pts, .closed = false },
    };
    const zi_shapes = [_]icon_ir.Shape{
        .{ .contours = &s0_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
        .{ .contours = &s1_contours, .fill = false, .stroke_width = 2, .fill_rule = .nonzero },
    };
    const zi_reps = [_]icon_ir.Rep{
        .{ .size = 24, .view_min_x = 0, .view_min_y = 0, .view_width = 24, .view_height = 24, .shapes = &zi_shapes },
    };
    break :blk Asset{ .svg_data = @embedFile("icons_common/x_close.svg"), .default_width = 24, .default_height = 24, .icon_id = 17, .reps = &zi_reps };
};
pub const Entry = struct {
    name: []const u8,
    asset: Asset,
};

pub const all = [_]Entry{
    .{ .name = "calendar", .asset = calendar },
    .{ .name = "check", .asset = check },
    .{ .name = "chevron_down", .asset = chevron_down },
    .{ .name = "chevron_left", .asset = chevron_left },
    .{ .name = "chevron_right", .asset = chevron_right },
    .{ .name = "chevron_up", .asset = chevron_up },
    .{ .name = "code", .asset = code },
    .{ .name = "file_text", .asset = file_text },
    .{ .name = "folder", .asset = folder },
    .{ .name = "folder_open", .asset = folder_open },
    .{ .name = "link", .asset = link },
    .{ .name = "mark", .asset = mark },
    .{ .name = "plus", .asset = plus },
    .{ .name = "scan", .asset = scan },
    .{ .name = "search", .asset = search },
    .{ .name = "star", .asset = star },
    .{ .name = "star_filled", .asset = star_filled },
    .{ .name = "x_close", .asset = x_close },
};

pub const count = all.len;

/// Resolve a kebab-case source name (for example `"alert-circle"`).
/// Uses binary search over the generated, lexicographically sorted registry.
pub fn get(name: []const u8) ?Asset {
    var lo: usize = 0;
    var hi: usize = all.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, name, all[mid].name)) {
            .lt => hi = mid,
            .gt => lo = mid + 1,
            .eq => return all[mid].asset,
        }
    }
    return null;
}

test "icon registry stays sorted and resolves names" {
    for (all, 0..) |entry, i| {
        if (i > 0) try std.testing.expect(std.mem.order(u8, all[i - 1].name, entry.name) == .lt);
        try std.testing.expectEqual(entry.asset.icon_id, get(entry.name).?.icon_id);
    }
    try std.testing.expect(get("not-a-zenit-icon") == null);
}
