//! Offline generator: scan a directory of SVG icons and emit a Zig source file
//! of `icon_ir.Asset` named constants (one per icon), plus a lazy, dynamic name
//! registry. Geometry is pre-flattened by the *runtime* parser
//! (`svg.parseToOwnedRep`) so it matches exactly what `rasterizeIconMask`
//! consumes.
//!
//! This regenerates one provider module from an SVG directory. Zenit's build
//! exposes `gen-icons-lucide`, `gen-icons-untitled`, and `gen-icons-all` steps;
//! provider selection during compilation never regenerates or rewrites source.
//!
//! Build & run:
//!   zig build gen-icons-lucide   (public provider)
//!   zig build gen-icons-untitled (internal provider)
//! or standalone:
//!   zig run tools/gen_svg_assets.zig --deps icon_ir,svg ... (use build step)
//!
//! Args: <icons_dir> <output_file> [embed_prefix] [base_icon_id]
//!   icons_dir    — directory containing *.svg (non-recursive)
//!   output_file  — path to write generated Zig
//!   embed_prefix — @embedFile path prefix relative to output file's dir
//!                  (default "icons/")
//!   base_icon_id — first icon_id (default 1000). icon_id is the GPU mask-cache
//!                  key {icon_id, rep_size}; the builtin `common` set uses
//!                  0..~16, so the full library starts at 1000 to avoid
//!                  cache-key collisions when both are used in one app.
const std = @import("std");
const icon_ir = @import("icon_ir");
const svg = @import("svg");

const IconEntry = struct {
    /// original file stem, e.g. "alert-circle"
    file_stem: []const u8,
    /// Zig identifier, e.g. "alert_circle"
    ident: []const u8,
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    const args = try std.process.argsAlloc(alloc);
    defer std.process.argsFree(alloc, args);
    if (args.len < 3) {
        std.debug.print("usage: gen_svg_assets <icons_dir> <output_file> [embed_prefix] [base_icon_id]\n", .{});
        return error.BadArgs;
    }
    const icons_dir_path = args[1];
    const output_path = args[2];
    const embed_prefix = if (args.len > 3) args[3] else "icons/";
    const base_icon_id: u16 = if (args.len > 4)
        try std.fmt.parseInt(u16, args[4], 10)
    else
        1000;

    // 1. Collect *.svg file stems, sorted for stable icon_id assignment.
    var entries = std.ArrayList(IconEntry){};
    defer {
        for (entries.items) |e| {
            alloc.free(e.file_stem);
            alloc.free(e.ident);
        }
        entries.deinit(alloc);
    }

    var dir = try std.fs.cwd().openDir(icons_dir_path, .{ .iterate = true });
    defer dir.close();
    var it = dir.iterate();
    while (try it.next()) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".svg")) continue;
        const stem = entry.name[0 .. entry.name.len - ".svg".len];
        const ident = try toIdent(alloc, stem);
        const stem_dup = try alloc.dupe(u8, stem);
        try entries.append(alloc, .{ .file_stem = stem_dup, .ident = ident });
    }

    std.mem.sort(IconEntry, entries.items, {}, struct {
        fn lessThan(_: void, a: IconEntry, b: IconEntry) bool {
            return std.mem.lessThan(u8, a.file_stem, b.file_stem);
        }
    }.lessThan);

    // 2. Accumulate output in memory (Zig 0.15 Io.Writer.Allocating), flush once.
    var aw = std.Io.Writer.Allocating.init(alloc);
    defer aw.deinit();
    const w = &aw.writer;

    try w.writeAll(
        \\// This file is auto-generated by tools/gen_svg_assets.zig. Do not edit manually.
        \\// Regenerate with: zig build gen-icons
        \\
        \\const std = @import("std");
        \\const icon_ir = @import("icon_ir");
        \\
        \\pub const Asset = icon_ir.Asset;
        \\
        \\
    );

    // 3. Emit one named const per icon.
    var generated_entries = std.ArrayList(IconEntry){};
    defer generated_entries.deinit(alloc);

    var icon_id: u16 = base_icon_id;
    var skipped: usize = 0;
    for (entries.items) |e| {
        const svg_path = try std.fs.path.join(alloc, &.{ icons_dir_path, e.file_stem });
        defer alloc.free(svg_path);
        const svg_full = try std.fmt.allocPrint(alloc, "{s}.svg", .{svg_path});
        defer alloc.free(svg_full);

        const svg_data = std.fs.cwd().readFileAlloc(alloc, svg_full, 1 << 20) catch |err| {
            std.debug.print("WARN: read {s}: {s}\n", .{ svg_full, @errorName(err) });
            skipped += 1;
            continue;
        };
        defer alloc.free(svg_data);

        var rep = svg.parseToOwnedRep(alloc, svg_data, 24) catch |err| {
            std.debug.print("WARN: parse {s}: {s} — skipped\n", .{ e.file_stem, @errorName(err) });
            skipped += 1;
            continue;
        };
        defer rep.deinit(alloc);

        try emitAsset(w, e, rep, icon_id, embed_prefix);
        try generated_entries.append(alloc, e);
        icon_id += 1;
    }

    // 4. Dynamic-by-name track. Referencing one named constant remains lazy;
    // using `all`/`get` intentionally links the complete registry (the same
    // two-track trade-off as an icon package's named exports vs. Icon(name)).
    try w.writeAll(
        \\pub const Entry = struct {
        \\    name: []const u8,
        \\    asset: Asset,
        \\};
        \\
        \\pub const all = [_]Entry{
        \\
    );
    for (generated_entries.items) |e| {
        try w.print("    .{{ .name = \"{s}\", .asset = {s} }},\n", .{ e.file_stem, e.ident });
    }
    try w.writeAll(
        \\};
        \\
        \\pub const count = all.len;
        \\
        \\/// Resolve a kebab-case source name (for example `"alert-circle"`).
        \\/// Uses binary search over the generated, lexicographically sorted registry.
        \\pub fn get(name: []const u8) ?Asset {
        \\    var lo: usize = 0;
        \\    var hi: usize = all.len;
        \\    while (lo < hi) {
        \\        const mid = lo + (hi - lo) / 2;
        \\        switch (std.mem.order(u8, name, all[mid].name)) {
        \\            .lt => hi = mid,
        \\            .gt => lo = mid + 1,
        \\            .eq => return all[mid].asset,
        \\        }
        \\    }
        \\    return null;
        \\}
        \\
        \\test "icon registry stays sorted and resolves names" {
        \\    for (all, 0..) |entry, i| {
        \\        if (i > 0) try std.testing.expect(std.mem.order(u8, all[i - 1].name, entry.name) == .lt);
        \\        try std.testing.expectEqual(entry.asset.icon_id, get(entry.name).?.icon_id);
        \\    }
        \\    try std.testing.expect(get("not-a-zenit-icon") == null);
        \\}
        \\
    );

    try std.fs.cwd().writeFile(.{ .sub_path = output_path, .data = aw.written() });
    std.debug.print("gen-icons: wrote {d} icons (ids {d}..{d}, {d} skipped) → {s}\n", .{ icon_id - base_icon_id, base_icon_id, icon_id - 1, skipped, output_path });
}

fn emitAsset(
    w: anytype,
    entry: IconEntry,
    rep: icon_ir.OwnedRep,
    icon_id: u16,
    embed_prefix: []const u8,
) !void {
    try w.print("pub const {s} = blk: {{\n", .{entry.ident});

    // contours → shapes → rep, mirroring svg_assets_generated.zig layout.
    for (rep.shapes, 0..) |shape, si| {
        for (shape.contours, 0..) |contour, ci| {
            try w.print("    const s{d}_c{d}_pts = [_]icon_ir.Point{{\n", .{ si, ci });
            for (contour.points) |p| {
                try w.print("        .{{ .x = {d}, .y = {d} }},\n", .{ p.x, p.y });
            }
            try w.writeAll("    };\n");
        }
        try w.print("    const s{d}_contours = [_]icon_ir.Contour{{\n", .{si});
        for (shape.contours, 0..) |contour, ci| {
            try w.print("        .{{ .points = &s{d}_c{d}_pts, .closed = {} }},\n", .{ si, ci, contour.closed });
        }
        try w.writeAll("    };\n");
    }

    try w.writeAll("    const zi_shapes = [_]icon_ir.Shape{\n");
    for (rep.shapes, 0..) |shape, si| {
        try w.print(
            "        .{{ .contours = &s{d}_contours, .fill = {}, .stroke_width = {d}, .fill_rule = .{s} }},\n",
            .{ si, shape.fill, shape.stroke_width, @tagName(shape.fill_rule) },
        );
    }
    try w.writeAll("    };\n");

    try w.print(
        "    const zi_reps = [_]icon_ir.Rep{{\n" ++
            "        .{{ .size = {d}, .view_min_x = {d}, .view_min_y = {d}, .view_width = {d}, .view_height = {d}, .shapes = &zi_shapes }},\n" ++
            "    }};\n",
        .{ rep.size, rep.view_min_x, rep.view_min_y, rep.view_width, rep.view_height },
    );

    try w.print(
        "    break :blk Asset{{ .svg_data = @embedFile(\"{s}{s}.svg\"), .default_width = {d}, .default_height = {d}, .icon_id = {d}, .reps = &zi_reps }};\n",
        .{ embed_prefix, entry.file_stem, @as(u32, @intFromFloat(rep.view_width)), @as(u32, @intFromFloat(rep.view_height)), icon_id },
    );
    try w.writeAll("};\n");
}

/// Convert an icon file stem to a valid Zig identifier:
/// hyphens → underscores, uppercase → lowercase. Dataset is known-clean
/// (only `-` and one capital), so no leading-digit or keyword handling needed.
/// Zig 关键字与基础类型名 —— 与之同名的图标必须走 `@"..."` 转义，
/// 否则生成物编译不过。真实踩坑：Lucide 有个 `type.svg`，直接生成
/// `pub const type = ...` 报 "name shadows primitive 'type'"。
/// 图标集是外部输入，不能假设文件名一定是合法 Zig 标识符。
fn needsEscape(ident: []const u8) bool {
    const reserved = [_][]const u8{
        // 关键字
        "addrspace",      "align",       "allowzero",    "and",       "anyframe",
        "anytype",        "asm",         "async",        "await",     "break",
        "callconv",       "catch",       "comptime",     "const",     "continue",
        "defer",          "else",        "enum",         "errdefer",  "error",
        "export",         "extern",      "fn",           "for",       "if",
        "inline",         "linksection", "noalias",      "noinline",  "nosuspend",
        "opaque",         "or",          "orelse",       "packed",    "pub",
        "resume",         "return",      "struct",       "suspend",   "switch",
        "test",           "threadlocal", "try",          "union",     "unreachable",
        "usingnamespace", "var",         "volatile",     "while",
        // 基础类型 / 值
            "bool",
        "void",           "type",        "anyerror",     "anyopaque", "comptime_int",
        "comptime_float", "noreturn",    "null",         "true",      "false",
        "undefined",      "isize",       "usize",        "c_char",    "c_short",
        "c_ushort",       "c_int",       "c_uint",       "c_long",    "c_ulong",
        "c_longlong",     "c_ulonglong", "c_longdouble", "f16",       "f32",
        "f64",            "f80",         "f128",
    };
    for (reserved) |r| {
        if (std.mem.eql(u8, ident, r)) return true;
    }
    // i32 / u8 / i0 这类整型基础类型是无穷集，按模式识别
    if (ident.len >= 2 and (ident[0] == 'i' or ident[0] == 'u')) {
        for (ident[1..]) |c| {
            if (c < '0' or c > '9') return false;
        }
        return true;
    }
    return false;
}

fn toIdent(alloc: std.mem.Allocator, stem: []const u8) ![]const u8 {
    const lowered = try alloc.alloc(u8, stem.len);
    defer alloc.free(lowered);
    for (stem, 0..) |c, i| {
        lowered[i] = switch (c) {
            '-' => '_',
            'A'...'Z' => c + 32,
            else => c,
        };
    }

    // 数字开头同样不是合法标识符（Lucide 有 `4k.svg`、`123.svg` 这类）
    const digit_leading = lowered.len > 0 and lowered[0] >= '0' and lowered[0] <= '9';
    if (needsEscape(lowered) or digit_leading) {
        return std.fmt.allocPrint(alloc, "@\"{s}\"", .{lowered});
    }
    return alloc.dupe(u8, lowered);
}
